# apiVersion: v1
# kind: service
# metadata:
#   name: nginx
# spec:
#   selector:
#     project: roboshop
#     component: frontend
#     environment: devolopment
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80 

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: roboshop
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port