apiVersion: v1 
kind: Pod 
metadata: 
  name: service-demo 
  # thease labels are used to register this pod to service
  labels: 
    project: roboshop 
    component: frontend 
    environment: dev
spec: 
  containers: 
  - name: nginx 
    image: nginx