apiVersion: v1 
kind: Pod 
metadata: 
  name: service-demo 
  labels: 
    project: roboshop 
    component: frontend 
    environment: devolopment 
spec: 
  containers: 
  - name: nginx 
    image: nginx