apiVersion: v1 
kind: ReplicaSet 
metadata: 
  name: nginx 
  labels: 
    purpose: rs-demo 
    project: roboshop 
spec: 
  replicas: 3 
  selector:  
  # used to select pods
    matchLabels: 
      purpose: rs-demo 
      project: roboshop 
      # pod defination
  template: 
    metadata: 
      labels: 
        purpose: rs-demo 
        project: roboshop 
    spec: 
      containers: 
      - name: nginx 
        image: nginx 